
[workspace]

members = [
    "server",
    "client",
    "protocol",
    "socket",
    "rabbit",
    "rabbit_derive",
    "logic",
    "wgpu_shader"
]


[patch.crates-io]
tokio = { path = 'tokio/tokio', branch = 'release-0.2.13' }

